# Generated by Django 4.0.3 on 2022-03-26 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_director_alter_movie_director'),
    ]

    operations = [
        migrations.RenameField(
            model_name='director',
            old_name='birthday',
            new_name='brithday',
        ),
    ]
